### ISSUE TITLE
Add simple "Modal" example following "Hello World"

### ISSUE THREAD

**Issue by mairatma** [metal/metaljs.com#10]
Once the [Hello World](https://github.com/metal/metaljs.com/issues/9) example exists, we should work on top of it to create a more complex example. **Modal** is a good component for this, since it's small but can show all the basics, such as: template, state and inline listeners.

Let's make sure this example really helps people see everything working as features are added. The current examples we have are very theoretical, a lot of code but nothing running straightaway, which makes them harder to follow.

**Comment by fernandosouza** [comment]
👍

**Comment by mairatma** [comment]
Just FYI, I've started this with https://github.com/metal/metaljs.com/commit/728691ce11ad0abf38c62a3861232f9826f37400, but there's still more to go (show inline events and nested components at least, and reorganize the replaced intro guides into regular guides).
