### ISSUE TITLE
Mention JSX in the homepage

### ISSUE THREAD

**Issue by zenorocha** [metal/metaljs.com#15]

**Comment by zenorocha** [comment]
@mairatma, can you update the content from that infrastructure part? 

We'll also need to remove things like: "One thing that can be really useful for a developer when building a component, is to separate the rendering logic from the business logic." since does exactly the opposite.

**Comment by mairatma** [comment]
Sure :)

**Comment by mairatma** [comment]
Done c8c5d887b8ac49d56bb692c301554b47ce73b964
