### ISSUE TITLE
Document the relationship with AUI (if any)

### ISSUE THREAD

**Issue by mairatma** [metal/metaljs.com#26]
_From @yuchi on April 16, 2015 8:9_

People will come here with questions about the future of Liferay FE development.

Could be a good idea to explicit what this project means for Alloy and Liferay.

_Copied from original issue: metal/metal.js#90_

**Comment by zenorocha** [comment]
Closing since this should be explained somewhere else.

**Comment by guitarmanvt** [comment]
When this gets documented elsewhere, if you could include the link here, it might help people find the requested documentation. Thanks!

**Comment by jbalsas** [comment]
Hey @guitarmanvt, we published a [blog entry trying to clarify the status of AlloyUI](https://web.liferay.com/es/web/nathan.cavanaugh/blog/-/blogs/the-status-and-direction-of-the-frontend-infrastructure-in-liferay-7-dxp) a while back.

That should give some some context and additional information. Hope that helps!

@jonmak08, @zenorocha, it might be a good idea to update [alloy-ui/README.md](https://github.com/liferay/alloy-ui/blob/master/README.md) to reflect the real status of the project. What do you think?
