### ISSUE TITLE
For certain child components, triggering an onChange and updating redux and/or state does not re-render

### ISSUE THREAD

**Issue by ssmith353** [metal/metaljs.com#39]
Hi MetalJS Team, 
We're having an issue where even if we set the state or update Redux with an onChange, the component does not re-render. Showing stale data. 

Only if we click in and out of another component does the original component re-render, and show the correct new value. 

Notice in the attached video that when a new item is selected, the "selected" value does not change, though redux does update. But when we click in - and - out of the input box below, the input above updates. Note: This component is wrapped with the metal-react bridge. 

[goo.gl/nTtZM1](https://goo.gl/nTtZM1)

**Comment by fernandosouza** [comment]
Hi, @ssmith353. Thx for reporting it. I will take a look.

**Comment by ssmith353** [comment]
Oops, this is for the main metalJS repo, not metalJS.com
