### ISSUE TITLE
Metal.js soy boilerplate does not include bootstrap css

### ISSUE THREAD

**Issue by alexandervalencia** [metal/metaljs.com#43]
On http://metaljs.com/docs/ I downloaded the boilerplate with soy and found that the bootstrap css was not included for any of the examples.

Each package.json is missing ```"bootstrap": "^3.3.6",``` from it's dependencies list.

The boilerplate with jsx DOES include this line and works as expected.

**Comment by bryceosterhaus** [comment]
Updated and added dependencies https://github.com/metal/metaljs.com/commit/78144dc5adefec82d7dedf26a241f8e469459c89
