### ISSUE TITLE
Update chat URL

### ISSUE THREAD

**Issue by jonnilundy** [metal/metaljs.com#62]
By [migrating the slack chat invitation server](https://github.com/metal/chat/pull/1) to WeDeploy beta, the chat links need to be updated.

@zenorocha Are you planning, or have you already, deployed the new chat server? If so, can you share the URL here?

**Comment by zenorocha** [comment]
Can you deploy it and add me as a collaborator?

**Comment by jonnilundy** [comment]
Yes, the only thing I need is the token for the Metal slack room.

**Comment by jbalsas** [comment]
We were actually considering moving this to the Liferay Community Slack room... what do you think, @zenorocha, @jonnilundy, @eduardolundgren?

**Comment by jbalsas** [comment]
This was merged and published yesterday!
