### ISSUE TITLE
Update gulp-metal URL

### ISSUE THREAD

**Issue by jwu910** [metal/metaljs.com#65]
https://github.com/metal/metaljs.com/blob/master/src/pages/docs/getting-started/modal_testing.md

Modal testing tutorial contains link on line 32 resulting in 404.

Line 32: ```{sp}**Metal.js**'s test tools by using [gulp-metal](/docs/guides/gulp_metal.html).```

**Comment by blzaugg** [comment]
I think this should be: `/docs/guides/building.md#gulp_metal`

**Comment by blzaugg** [comment]
https://github.com/metal/metaljs.com/blob/35b6296819c9dc3dd28a3579eefd3c4fda81a071/src/pages/docs/guides/building.md#gulp-metal

**Comment by zenorocha** [comment]
Closing after #66 was merged.
