### ISSUE TITLE
Think about a way to show both soy and jsx templates in the examples

### ISSUE THREAD

**Issue by mairatma** [metal/metaljs.com#8]
Maybe show them both together every time? Maybe have separate pages for each?

**Comment by zenorocha** [comment]
I think we should use that component you created that adds a tab to codemirror. That way we don't generate different pages for each.

**Comment by mairatma** [comment]
I thought about that idea too, the only problem is that there are some differences in both usage and behavior between the two as well, not just the templates, which would need to be explained.

For example, it's important to explain that soy params are automatically turned into state properties, but that can't happen for JSX because it doesn't specify its params. Also, for JSX components the template is specified inside the component's `render` function while for soy it's a separate file.

So maybe we just need an initial section that would explain these differences separately, and on all other occasions just show the different templates like you suggested.

**Comment by zenorocha** [comment]
I see.... let's try that and see how it goes. We need to have the content ready in order to figure this out.

**Comment by mairatma** [comment]
I've created a template that can be used to render codemirror with tabs. It's not using metal.js, as that would require some big changes on that existing component (specially since it's using outdated dependencies, it's been a while since it has been used), as well as on the site's infra. I just added some small code to handle the case we need.

I'll use this codemirror with tabs to try to show examples for both templates, let's see if it works well.

@zenorocha, feel free to make this visually better, I tried doing something similar to what we had on metal-codemirror-tabs, but not the same since it didn't fit metaljs.com's styling as it was.

**Comment by cirocosta** [comment]
Hey, saw that working  in the updated version which just went up, looks great! 👍 

One suggestion that i have is to propagate the selected tab to all snippets in the page (someone who's interested in the jsx syntax will probably want to change to that tab in all the snippets).

Do you think that's interesting?

**Comment by mairatma** [comment]
You're right, that makes total sense, it would not be nice to have to switch to JSX every time. Could you open an issue for this? :)

**Comment by cirocosta** [comment]
yeah, just did it. Thx  👯
