### ISSUE TITLE
Add a simple "Hello World" example

### ISSUE THREAD

**Issue by mairatma** [metal/metaljs.com#9]
We've gotten feedback that the intro we have in the site's docs doesn't have a quick way to see something working on the screen, which makes Metal.js seem harder to start working with.

Let's have a simple **Hello World** example right at the beginning, so people can see things working right from the start. That's easy to do when using the generator. We can talk about the details of how everything is working, and how to customize things in later sections.

**Comment by fernandosouza** [comment]
👍
